server:
  port: 80

spring:
  application:
    name: cloud-order-server

eureka:
  client:
    #表示将自己注册进eureka server
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，集群的时候可以配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #注册地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka